### ISSUE TITLE
[KFKESQ-12] Allow the configuration of internal KafkaConsumer and KafkaProducer using system properties

### ISSUE THREAD

**Issue by rcardin** [rcardin/kafkaesque#19]
Allow the configuration of internal `KafkaConsumer` and `KafkaProducer` using system properties.

As an example, we can try to implement the same approach concerning the properties used by the `spring-kafka` library (see [here](https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.integration.spring.kafka.consumer.properties)).

The `KafkaConsumer` / `KafkaProducer` properties should be rooted at some paths like `kafkaesque.consumer.properties.*` and `kafkaesque.producer.properties.*`.

**Comment by farajist** [comment]
Hey @rcardin, I came across kafkaesque by chance and I'm quite interested in contributing to the project, that's why I would like to give this issue a try, do you have any suggestions or hints on how to implement the configuration of the internal classes ? As far as I know Spring relies on `@ConfigurationProperties` for bidning which is part of the framework. Something like [Apache Commons Configuration](https://commons.apache.org/proper/commons-configuration/index.html) looks convenient.

**Comment by rcardin** [comment]
Hey. @farajist. Glad to hear from you! Give me some time to refresh my mind on what I intended to do at the time, and I'll return to you with some hints 😄

**Comment by rcardin** [comment]
@farajist , sorry for the delay of this response. There were crazy days.

So, we can't configure the host/post information as a property, since the port is usually created randomly. However, there are all the other Kafka consumer and producer configurations there are worth configuring for some use cases. We can't rely on Spring in the `core` library, since we're agnostic on the concrete implementation of the test broker.

As you suggested, probably the Apache Commong Configuration is a good choice. Let's give it a try. As a second step, we'll create a dedicated integration for Spring, in which we'll read the tailored properties for Spring Kafka.

What's your thoughts?

**Comment by farajist** [comment]
It's all right @rcardin , I quite understand. I have taken the time to skim through the source and explore more possible options for a configuration backend 

I agree with you, consumer and producer configuration should follow the same convention as `spring-kafka` with respect
to configurable properties all without relying on any spring feature (e.g. something like `kafkaesque.*` properties)
Sources of configuration however must be kept opinionated, the user for example might prefer to define 
only a subset of the properties and rely on sensible defaults for others (pretty much the case for every lazy dev :joy: )

I will work out a quick implementation just to test the water and see what can be improved from there on ;)

**Comment by rcardin** [comment]
It seems like a good plan. I can't wait to see your code!

**Comment by rcardin** [comment]
Hey, @farajist. Let me know if you're still interested in contributing to the project. I left some comments in your PR. Let me know if there's any problem so that I can understand how to help you 😃

**Comment by farajist** [comment]
Hello @rcardin, sorry for the late feedback, yeah I'm still interested I was just a bit busy this last week to work have a look at the comments and implement the right changes, I will be working on it this week and reach out in case something is not clear enough. Thanks 😆
