### ISSUE TITLE
[KFKESQ-15] Add header support while producing message

### ISSUE THREAD

**Issue by DNAlchemist** [rcardin/kafkaesque#26]
Hi!
There is no Kafka header support in you library, and there is no workaround to send headers using your library
Could you add headers support?

**Comment by rcardin** [comment]
Hey, man. Thanks for the issue. Can you give me some details? Do you need to add the possibility to set headers in messages the Kafkaesque producer sends? You may need to make some assertions on the headers on the consumer side.

Both are very interesting and useful use cases 😄 
Let me know.
Riccardo
--

**Comment by rcardin** [comment]
Man, version 0.2.0 contains the changes you requested. Let me know if it's all ok.

**Comment by DNAlchemist** [comment]
Thank you 🥳
